# Generated by Django 2.2 on 2020-08-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ProjectName')),
            ],
        ),
    ]
